config/urls.py
from django.contrib import admin
from django.urls import path, include
from member import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('social/', include('social.urls')),
    path('', views.index, name='index'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from member import views

app_name = 'member'

urlpatterns = [
    # auth
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('main/', views.main, name='main'),
    path('profile/', views.profile, name='profile'),
    path('edit/', views.edit, name='edit'),
]

social/urls.py
from django.urls import path, include
from social import views

app_name = 'social'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('like/<int:article_pk>', views.like, name='like'),
    path('comment/<int:article_pk>', views.comment, name='comment'),
    path('tag/detail/<int:tag_pk>', views.tag_detail, name='tag-detail'),
]

member/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField
from django.db.models.fields.related import OneToOneField

# Create your models here.

class Member(models.Model) :
        user = models.OneToOneField(User, on_delete=models.SET_NULL, related_name='member', null=True, blank=True)
        name = models.CharField(max_length=64)
        username = models.CharField(max_length=64)

social/models.py
from django.db import models
from django.contrib.auth.models import User
from member.models import Member
# Create your models here.

class Tag(models.Model) :
    name= models.CharField(max_length=64, unique=True)

class Article(models.Model) :
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True, blank=True)
    like_users = models.ManyToManyField(User,related_name='like_articles' )
    tags = models.ManyToManyField(Tag, related_name='article', blank=True)

class Photo(models.Model) :
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True ,related_name='photo')
    image = models.ImageField(upload_to='images/', blank=True, null=True)

class Comment(models.Model) :
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, blank=True, related_name='comment')
    writer = models.ForeignKey(Member, on_delete=models.SET_NULL, related_name='comment', null=True, blank=True)
    content = models.TextField()
    is_deleted = models.BooleanField(default=False)

class Relation(models.Model) :
    member = models.OneToOneField(Member, on_delete=models.CASCADE, related_name="relation")
    followers = models.ManyToManyField(Member, related_name="following", null=True, blank=True)

member/views.py
from social.models import Article
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

from .models import Member
from social.models import Comment,Tag
# Create your views here.
ERROR_MSG = {
    'MISSING_INPUT': '필수항목을 작성해주세요.',
    'MISSING_PW' : '잘못된 비밀번호입니다. 다시 확인하세요'
}
def index(request) :
    context = {
        'error' : {
            'state' : False,
            'msg' : ''
        }
    }
    if request.method == 'POST' :
        useremail = request.POST['useremail']
        password = request.POST['password']
        auth_user = auth.authenticate(username=useremail, password=password)

        if (auth_user) :
            auth.login(request, auth_user)
            return redirect('member:main')

        else :
            context['error']['state'] = True
            context['error']['msg'] = ERROR_MSG['MISSING_PW']

        if (not useremail or not password) :
            context['error']['state'] = True
            context['error']['msg'] = ERROR_MSG['MISSING_INPUT']

    return render(request, 'index.html', context)

def signup(request) :

    if request.method == 'POST' :
        useremail = request.POST['useremail']
        name = request.POST['name']
        username = request.POST['username']
        password = request.POST['password']

        user = User.objects.create_user(
            username=useremail,        
            password=password
        )

        Member.objects.create(
            user=user,
            name=name,
            username=username,
        )

        auth.login(request, user)

        return redirect('index')
    return render(request, 'signup.html')

def logout(request) :
    auth.logout(request)

    return redirect('index')

def main(request) :
    article = Article.objects.all()
    tag = Tag.objects.all().first()
    context = {
        'article': article,
        'tag': tag,
    }
    return render(request, 'main.html', context)

def profile(request) :
    user = request.user
    member = Member.objects.filter(user=user).first()
    context = {
        'member' : member,
    }
    return render(request, 'profile.html', context)

def edit(request) :
    user = request.user
    member = Member.objects.filter(user=user)
    context ={
        'member' : member.first()
    }

    if request.method == 'POST' :
        name = request.POST['name']
        username = request.POST['username']

        member.update(
            name=name,
            username=username
        )
        return redirect('member:edit')       
        
    return render(request, 'edit.html', context)

def search(request) :
    member_list = Member.objects.all()
    search = request.GET.get('search')
    if search:
        member_list = member_list.filter(title__icontains=search)
    
    return redirect('member:main')

social/views.py
from django.db.models.query import RawQuerySet
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.http import request, JsonResponse

from member.models import Member
from .models import Article, Photo, Comment,Tag
# Create your views here.

def upload(request) :
    if request.method == 'POST' :
        content = request.POST['content']
        tag_name = request.POST['tag_name']
        tag = Tag.objects.filter(name=tag_name)
        article = Article.objects.create(
            content=content,
            writer=request.user,
        )
        print(article)
        if (len(tag) > 0):
            article.tags.add(tag.first())
            return redirect('member:main')
        tag = Tag.objects.create(name=tag_name)
        article.tags.add(tag)
        
        for img in request.FILES.getlist('image'):
            Photo.objects.create(
                article=article,
                image=img
            )
        return redirect('member:main')
    return render(request, 'upload.html')
    
def like(request, article_pk) :
    article = get_object_or_404(Article, pk=article_pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
        liked = False
    else:
        article.like_users.add(request.user)
        liked = True
    return JsonResponse({'liked':liked, 'count':article.like_users.count()})

def comment(request, **kwargs) :
    comment = request.POST['comment']
    article_pk = kwargs['article_pk']
    article = Article.objects.get(pk=article_pk)
    writer = Member.objects.get(user=request.user)
    comment = Comment.objects.create(
        writer=writer,
        content=comment,
        article=article
    )    
    
    return redirect('member:main')

def tag_detail(request, tag_pk) :
    articles = Article.objects.filter(tags__pk__in=[tag_pk])
    tags = Tag.objects.filter(pk=tag_pk).first()
    context = {'articles': articles, 'tags': tags}
    print(articles)

    return render(request, 'tag_detail.html', context)

member/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>프로필 편집</title>
</head>
<body>
    <a href="{% url 'member:main' %}"><h3>Instagram</h3></a>
    <a href="{% url 'member:profile' %}">프로필</a>
    <a href="{% url 'member:logout' %}">로그아웃</a>
    <hr>    
    {{member.username}}
    <form action="{% url 'member:edit' %}" method="POST">
    {% csrf_token %}
        <p>프로필 사진 바꾸기</p>
        <p>이름 <input type="text" name='name' value='{{member.name}}'></p>
        <p>사용자 이름 <input type="text" name='username' value={{member.username}}></p>
        <button type='submit'>제출</button>
    </form>
</body>
</html>

member/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram</title>
</head>
<body>
    <h1>Instagram</h1>
    <form action="{% url 'index' %}" method='POST'>
        {% csrf_token %}
        <input type="email" placeholder='이메일' name='useremail'>
        <input type="password" placeholder="비밀번호" name='password'>
        <button type='submit'>로그인</button>
    </form>
    <p>
    {% if error.state %} 
    {{error.msg}} 
    {% endif %}
    </p>  
    <p>계정이 없으신가요? <a href="{% url 'member:signup' %}">가입하기</a></p>
</body>
</html>

member/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram</title>
    <script src="https://kit.fontawesome.com/3a22cbe536.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

</head>
<body>
    <a href="{% url 'member:main' %}"><h3>Instagram</h3></a>
    <form action="" method="get">
        {% csrf_token %}
        <input type="text" placeholder="검색" name='search'>
    </form>
    
    <a href="{% url 'member:profile' %}">프로필</a>
    <a href="{% url 'member:logout' %}">로그아웃</a>
    <hr>    
    <br>
    {% for article_obj in article %}
        {% for photo in article_obj.photo.all %}
            <img src="{{photo.image.url}}" width='500'><br>
            <p>{{photo.article.content}}</p>
            {%for tag in photo.article.tags.all%}
            <a href="{% url 'social:tag-detail' tag.pk %}"><p>#{{tag.name}}</p></a>
            {% endfor %}
            {% endfor %}
            <i class ="{% if request.user in photo.article.like_users.all %}
            fas
            {% else %}
            far
            {% endif %} fa-heart
            like-button" data-id="{{article_obj.id}}" style="cursor: pointer;" >
            </i>
            <i class="far fa-comment" style="cursor: pointer;"></i>
            <br>
            좋아요
            <span id="like-count-{{article_obj.id}}">
                 {{count}}
            </span>개
            <br>
            {% for comment in article_obj.comment.all %}
            {{comment.content}}
            <br>
            {% endfor %}
            <br>
            <form action="{% url 'social:comment' article_obj.pk %}" method="POST">
                {% csrf_token %}
                <!-- <input type="hidden" value="{{article_obj.pk}}" name="article_id"> -->
                <input type="text" placeholder="댓글 달기..." name="comment" />
            </form>
        {% endfor %}

    <script>
        const likebuttons = document.querySelectorAll('.like-button')
        likebuttons.forEach(function(button){
            button.addEventListener('click', function(event){
                console.log(event.target.classList)
                const postId = event.target.dataset.id
                axios.get(`/social/like/${postId}`)
                        .then(function(response){
                            document.querySelector(
                                `#like-count-${postId}`).innerText= response.data.count
                            
                            // response.data => {'liked':True} 혹은 {'liked':False}
                            if (response.data.liked) {
                                event.target.classList.remove('far')
                                event.target.classList.add('fas')
                            } else {
                                event.target.classList.remove('fas')
                                event.target.classList.add('far')
                            }
                        })
                // window.location.reload();
            })
        })
    </script>
</body>

</html>

member/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{member.name}}(@{{member.username}})</title>
</head>
<body>
    <h3>Instagram</h3>
    <span>{{member.username}}</span>
    <button><a href="{% url 'member:edit' %}">프로필 편집</a></button>
    <br>
    <br>
    <span>게시물</span>
    <span>팔로워</span>
    <span>팔로우</span>
    <p>{{member.name}}</p>
    <p><a href="{% url 'social:upload' %}">사진 및 동영상 공유</a></p>

</body>
</html>

member/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
</head>
<body>
    
    <form action="{% url 'member:signup' %}" method='POST'>
        {% csrf_token %}
        <input type="email" placeholder="이메일 주소" name='useremail'>
        <input type="text" placeholder="성명" name='name'>
        <input type="text" placeholder="사용자 이름" name='username'>
        <input type="password" placeholder="비밀번호" name='password'>
        <button type='submit'>가입</button>
    </form>

    <p>계정이 있으신가요? <a href="{% url 'index' %}">로그인</a></p>
    
</body>
</html>

social/templates/tag_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'member:main' %}"><h3>Instagram</h3></a>
    <a href="{% url 'member:profile' %}">프로필</a>
    <a href="{% url 'member:logout' %}">로그아웃</a>
    <hr>    
    <h1>#{{tags.name}}</h1>
    <p>게시물 {{tags.article.count}}</p>
    {%for article in articles%}
    {% for photo in article.photo.all %}
    <img src="{{photo.image.url}}" width='300' height="300">
    {% endfor %}
    {% endfor %}
    
</body>
</html>

social/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>업로드</title>
</head>
<body>
    <a href="{% url 'member:main' %}"><h3>Instagram</h3></a>
    <a href="{% url 'member:profile' %}">프로필</a>
    <a href="{% url 'member:logout' %}">로그아웃</a>
    <hr>    
    <form action="{% url 'social:upload' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="image" multiple>
        <input type='text' name='tag_name' placeholder="tag name" />
        <textarea name="content" placeholder="문구 입력..."></textarea>
        <input type="submit" value="작성하기">
    </form>
    
</body>
</html> 